### ISSUE TITLE
Developer application list receives 404

### ISSUE THREAD

**Issue by vitalyzautner** [n0madic/google-play-scraper#12]
There is probably some modification in GPlay, it's impossible to fetch the app data list for a developer.

**Comment by n0madic** [comment]
It doesn't seem to work in the store either...
For example, if you click on the developer link on https://play.google.com/store/apps/details?id=com.snapchat.android
https://play.google.com/store/apps/developer?id=Snap+Inc - 404

**Comment by n0madic** [comment]
Fixed in Play Store :)
