### ISSUE TITLE
Fatal error while getting category

### ISSUE THREAD

**Issue by emreoktem** [n0madic/google-play-scraper#16]
@n0madic Hi,

I'd created [another issue](https://github.com/n0madic/google-play-scraper/issues/15) and you'd closed it but there's still a fatal crash error as I mentioned [in my comment](https://github.com/n0madic/google-play-scraper/issues/15#issuecomment-1385699418).

Here's the example code with fatal crash:

`clusters, err := category.New(store.ArtAndDesign, store.AgeNineUp, category.Options{
   Country:  "us",
   Language: "us",
   Number:   100,
})`

**Comment by n0madic** [comment]
I also can’t find anything in this category, that’s why the error is because the list of clusters is empty

**Comment by n0madic** [comment]
it looks like only the store.Game category works at the moment...
Google has greatly simplified the web version of the store

**Comment by emreoktem** [comment]
@n0madic Is it at least possible to get an empty result instead of having a fatal crash?

**Comment by n0madic** [comment]
after my fix, it should be so in theory

**Comment by emreoktem** [comment]
@n0madic Btw, game category is also getting a crash

<img width="625" alt="image" src="https://user-images.githubusercontent.com/8793891/218435316-da4ff7e2-1521-4823-9245-274323170100.png">

**Comment by n0madic** [comment]
can not reproduce...
try this code with the latest version of the library
```go
package main

import (
	"fmt"

	"github.com/n0madic/google-play-scraper/pkg/category"
	"github.com/n0madic/google-play-scraper/pkg/store"
)

func main() {
	clusters, err := category.New(store.Game, store.AgeNineUp, category.Options{
		Country:  "us",
		Language: "us",
		Number:   100,
	})
	if err != nil {
		panic(err)
	}

	for clusterName := range clusters {
		fmt.Println("Cluster:", clusterName)
		err = clusters[clusterName].Run()
		if err != nil {
			panic(err)
		}
		for _, app := range clusters[clusterName].Results {
			fmt.Println(app.Title, app.URL)
		}
	}
}
```
